apiVersion: apps/v1
kind: Deployment
metadata:
 name: backend-deployment
spec:
 selector:
   matchLabels:
    type: frontend
 replicas: 2
 template:
   metadata:
     labels:
       type: frontend
   spec:
    containers:
    - name: backend
      image: cloudcamp2022/frontend:latest
      envFrom:
      ports:
      - containerPort: 80
      resources:
        requests:
          cpu: 100m
        limits:
          cpu: 200m